<?php
// test_perchance.php
// Attempt to reverse-engineer/connect to Perchance Image Generator
// Note: Perchance often uses dynamic verification keys. This is a basic attempt.

echo "<h3>Testing Perchance.org (Experimental)</h3>";

$prompt = "A futuristic city with flying cars, cyberpunk style";
echo "Prompt: $prompt<br>";

// Method 1: Direct API (Commonly used by their generators)
// Usually requires a 'verification' token generated by client-side JS.
// We might not be able to do this purely server-side easily without a headless browser or heavy reversing.
// Let's try a simple GET to a known generator to see if we can scrape or uses a simple API.
// "Output" button on Perchance usually triggers a request.

// Actually, Perchance generators are just HTML/JS.
// The image generation usually happens via an iframe to an external service or their internal API.
// Many Perchance generators use "pollinations" under the hood!
// If they use their own, it's often protected.

echo "Perchance integration is complex because it relies on client-side verification.<br>";
echo "However, we can try to find a public generator API wrapper.<br>";

// Let's try to see if we can hit a known endpoint.
// (This is a placeholder check to see if the server can even reach perchance.org)

$url = "https://perchance.org/ai-text-to-image-generator";
$html = @file_get_contents($url);

if ($html) {
    echo "✅ Successfully reached Perchance.org website.<br>";
    echo "This confirms server connectivity.<br>";
} else {
    echo "❌ Failed to reach Perchance.org.<br>";
}

echo "<br><b>Note:</b> Native Perchance API requires a 'User Token' generated via JavaScript (Puppeteer).<br>";
echo "For a PHP-only server, it is recommended to stick to Pollinations/HuggingFace/Pexels.<br>";
echo "However, I will add it to the menu as 'Perchance (Experimental)' in case we find a workaround.";

?>
